### ISSUE TITLE
Mistake about mmdetection3d

### ISSUE THREAD

**Issue by JT-Sun** [alfredgu001324/MapUncertaintyPrediction#5]
Hi, your work is very good and interesting, I would like to ask when installing mmdetection3d, mmdet3d 0.17.2 conflicts with the numpy==1.23.5 version you provided. Requirement.parse('numpy<1.20.0') Has this ever happened to you?

**Comment by alfredgu001324** [comment]
Thank you for your interest in our work! Yes this problem indeed happened to me. This is actually a long-lasting problem already ever since VectorMapNet (which MapTR series and StreamMapNet build upon on). The short answer is you can just ignore the warning, and training will still be fine. 

For the long answer, you can refer to this [Issue](https://github.com/Mrmoore98/VectorMapNet_code/issues/16).

**Comment by JT-Sun** [comment]
Thank you for your rapid reply and look forward to your complete code! 
Best wishes
